version: '3.8'
services:
  stats-server:
    build: stats/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  stats-db:
    image: postgres:15.3-alpine3.18
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      POSTGRES_DB: stat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  ewm-service:
    build: main-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:15.3-alpine3.18
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: ewm-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres